image: atools/chrome-headless:java8-node12-latest



pipelines:
    default:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm test
  