name: Automation

on: [push]

jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Schedular Automation
      working-directory: ./automation
    - run: npm install
    - run: npm test

