name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: switch folders and install dependencies
      run: npm install
      working-directory: automation
    - name: run tests
      run: npm test   
      working-directory: automation
