name: Node.js CI

on: [push]

jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Schedular
      working-directory: ./automation
    - run: npm install
    - run: npm test
      env:
        CI: true
